require('./flatten').assertFunctionality();
require('./head').assertFunctionality();
require('./letterPositions').assertFunctionality();
require('./map').assertFunctionality();
require('./middle').assertFunctionality();
require('./min').assertFunctionality();
require('./tail').assertFunctionality();
require('./takeUntil').assertFunctionality();
require('./without').assertFunctionality();